'use client';

// Airspace zones overlay — loads pre-fetched GeoJSON from /data/airspaces-cz.json
// (generated by scripts/fetch-airspaces.js) and renders colored polygons on the Leaflet map.
// No API call at runtime — data is bundled as a static public file.
// Must be a child of MapContainer so useMap() can access the map instance.
import { useEffect, useRef } from 'react';
import { useMap } from 'react-leaflet';
import L from 'leaflet';
import { airspaceColor, parseAirspaceItems, AirspaceZone } from '@/lib/airspace';

interface AirspaceLayerProps {
  /** Whether to show airspace zones on the map */
  active: boolean;
}

export default function AirspaceLayer({ active }: AirspaceLayerProps) {
  const map = useMap();

  // Cache parsed zones after first load so we don't re-fetch on toggle
  const zonesCache = useRef<AirspaceZone[] | null>(null);
  // Reference to the active Leaflet GeoJSON layer for cleanup
  const layerRef = useRef<L.GeoJSON | null>(null);

  useEffect(() => {
    if (!active) {
      if (layerRef.current) {
        layerRef.current.remove();
        layerRef.current = null;
      }
      return;
    }

    let cancelled = false;

    function renderLayer(zones: AirspaceZone[]) {
      if (cancelled) return;
      if (layerRef.current) {
        layerRef.current.remove();
        layerRef.current = null;
      }

      const features = zones.map((zone) => ({
        type: 'Feature' as const,
        properties: {
          name:      zone.name,
          typeName:  zone.typeName,
          icaoClass: zone.icaoClass,
          color:     airspaceColor(zone.type),
        },
        geometry: zone.geometry,
      }));

      const layer = L.geoJSON(
        { type: 'FeatureCollection', features } as Parameters<typeof L.geoJSON>[0],
        {
          style: (feature) => {
            const color = feature?.properties?.color ?? '#94a3b8';
            return { color, weight: 1.5, opacity: 0.9, fillColor: color, fillOpacity: 0.12 };
          },
          onEachFeature: (feature, featureLayer) => {
            const { name, typeName, icaoClass } = feature.properties ?? {};
            const classLabel = icaoClass ? ` · třída ${icaoClass}` : '';
            featureLayer.bindTooltip(
              `<strong>${name}</strong><br/><span>${typeName}${classLabel}</span>`,
              { sticky: true, className: 'airspace-tooltip' },
            );
            featureLayer.on('mouseover', () => {
              (featureLayer as L.Path).setStyle({ fillOpacity: 0.3, weight: 2.5 });
            });
            featureLayer.on('mouseout', () => {
              layer.resetStyle(featureLayer as L.Path);
            });
          },
        },
      );

      layer.addTo(map);
      layerRef.current = layer;
    }

    async function loadAndRender() {
      // Use cached data if available — avoids re-fetching on every toggle
      if (zonesCache.current) {
        renderLayer(zonesCache.current);
        return;
      }

      try {
        const res = await fetch('/data/airspaces-cz.json');
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data: { items?: unknown[] } = await res.json();
        if (!Array.isArray(data.items)) throw new Error('Unexpected data format');

        const zones = parseAirspaceItems(data.items);
        if (cancelled) return;
        zonesCache.current = zones;
        renderLayer(zones);
      } catch (err) {
        console.warn('[AirspaceLayer] Failed to load airspace data:', err);
      }
    }

    loadAndRender();

    return () => {
      cancelled = true;
      if (layerRef.current) {
        layerRef.current.remove();
        layerRef.current = null;
      }
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [active, map]);

  return null;
}
