'use client';

// Protected areas overlay — loads pre-fetched GeoJSON from /data/protected-areas-cz.json
// (generated by scripts/fetch-protected-areas.js) and renders colored polygons.
// NP = green, CHKO = blue. Tooltip shows name, type and drone restrictions.
// Must be a child of MapContainer so useMap() can access the map instance.
import { useEffect, useRef } from 'react';
import { useMap } from 'react-leaflet';
import L from 'leaflet';
import { protectedAreaColor, protectedAreaFillOpacity } from '@/lib/protectedAreas';

interface ProtectedAreasLayerProps {
  active: boolean;
}

export default function ProtectedAreasLayer({ active }: ProtectedAreasLayerProps) {
  const map = useMap();
  const cacheRef = useRef<GeoJSON.FeatureCollection | null>(null);
  const layerRef = useRef<L.GeoJSON | null>(null);

  useEffect(() => {
    if (!active) {
      if (layerRef.current) {
        layerRef.current.remove();
        layerRef.current = null;
      }
      return;
    }

    let cancelled = false;

    function renderLayer(geojson: GeoJSON.FeatureCollection) {
      if (cancelled) return;
      if (layerRef.current) {
        layerRef.current.remove();
        layerRef.current = null;
      }

      const layer = L.geoJSON(geojson as Parameters<typeof L.geoJSON>[0], {
        style: (feature) => {
          const type  = feature?.properties?.type ?? '';
          const color = protectedAreaColor(type);
          return {
            color,
            weight: 1.5,
            opacity: 0.85,
            fillColor: color,
            fillOpacity: protectedAreaFillOpacity(type),
          };
        },
        onEachFeature: (feature, featureLayer) => {
          const { name, type, restriction } = feature.properties ?? {};
          featureLayer.bindTooltip(
            `<strong>${name}</strong><br/><span>${type}</span><br/><em>${restriction}</em>`,
            { sticky: true, className: 'airspace-tooltip' },
          );
          featureLayer.on('mouseover', () => {
            (featureLayer as L.Path).setStyle({ fillOpacity: 0.45, weight: 2.5 });
          });
          featureLayer.on('mouseout', () => {
            layer.resetStyle(featureLayer as L.Path);
          });
        },
      });

      layer.addTo(map);
      layerRef.current = layer;
    }

    async function loadAndRender() {
      if (cacheRef.current) {
        renderLayer(cacheRef.current);
        return;
      }
      try {
        const res = await fetch('/data/protected-areas-cz.json');
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data: GeoJSON.FeatureCollection = await res.json();
        if (cancelled) return;
        cacheRef.current = data;
        renderLayer(data);
      } catch (err) {
        console.warn('[ProtectedAreasLayer] Failed to load data:', err);
      }
    }

    loadAndRender();

    return () => {
      cancelled = true;
      if (layerRef.current) {
        layerRef.current.remove();
        layerRef.current = null;
      }
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [active, map]);

  return null;
}
