'use client';

// Protected areas overlay — loads pre-fetched GeoJSON from /data/protected-areas-cz.json
// (generated by scripts/fetch-protected-areas.js) and renders colored polygons.
// NP = green, CHKO = blue. Tooltip shows name, type, and drone restrictions.
// Must be a child of MapContainer (useMapLayer calls useMap internally).

import { protectedAreaColor, protectedAreaFillOpacity } from '@/lib/protectedAreas';
import { useMapLayer } from '@/hooks/useMapLayer';

interface ProtectedAreasLayerProps {
  active: boolean;
}

export default function ProtectedAreasLayer({ active }: ProtectedAreasLayerProps) {
  useMapLayer({
    active,
    fetchUrl: '/data/protected-areas-cz.json',

    // Data is already a valid GeoJSON FeatureCollection — pass through directly
    parseData: (rawData) => rawData as GeoJSON.FeatureCollection,

    styleFeature: (feature) => {
      const type  = (feature.properties?.type as string) ?? '';
      const color = protectedAreaColor(type);
      return {
        color,
        weight: 1.5,
        opacity: 0.85,
        fillColor: color,
        fillOpacity: protectedAreaFillOpacity(type),
      };
    },

    tooltipHtml: (props) =>
      `<strong>${props.name}</strong><br/><span>${props.type}</span><br/><em>${props.restriction}</em>`,

    hoverFillOpacity: 0.45,
  });

  return null;
}
